const quotes = [
  'Prata inte med mig on du inte svettas först', // 0
  'Jorden stormar genom rymden och här sitter vi o chillar',
  'Släpp ner maskinvärktyget!',
  'Vinröd basker står för fallskärmsjägare',
  'Säg vad du vill om pedofiler, men dem klär sig ändå ganska snyggt',
  'Vilken musik spelas för skurken?',
  'Undvik Knölen',
  'Nationalistiska militanta budister',
  'Släpp såsen Eddy, jag är bara en medelsvensson',
  'Köttmunk UF',
  'Det är ju lite sitcom komplativa egenskaper', // 10
  'Jag sitter och småfiser hela tiden',
  'Det borde finns en sätesvärmare för själen',
  'Jag är inte den melodin',
  'Sverige är ett bra land för bra invandrare',
  'Det är inte svårt att ha tråkigt',
  'Jordens lungor rör sig',
  'Då var det en snut som stoppa en annan snut',
  'Det sker från en ledare i USA som nyligen drabbades av massmord i två städer',
  'Ingen bryr sig ett skit om duvor',
  'Man tänker ju inte på väggar så mycket', // 20
  'Jag är typ lite taggad på själva smärtan',
  'Rock and Roll madame Castafiolen. Rock and roll',
  'Alla de här gatorna man inte känner igen som inte ens finns med på Monopol',
  'Kör på mina potatisar',
  'Jag är inte söt Kendra, jag måste göra det',
  'Är det inte läskigt ska man skita i det',
  'Tio heta singlar, ett gemensamt mål',
  'Vem ska nu sköta terrariet?',
  'Ja gick me in i kartellen satt på 2,7 miljoner o 2, 3 kilo guld',
  'Blandade knip-övningar', // 30
  'Om vi är förlorare, vem är då vinnare?',
  'Du glömde din lur hos mig',
  'Testa det aldrig! Eller jo, testa det en gång',
  'Snälla säg att det är tisdag',
  'Tar in energier väldigt lätt och blir väldigt negativt påverkad',
  'Ungdommen måste skadas om mänskligheten ska överleva',
  'Anländer med myomspunna könssjukdommar',
  'Sova under jord',
  'Det är såhär, jag älskar livet',
  'Testa att särskriva skinksås', // 40
  'Jag ska ha ett hjärta',
  'Han är jävligt bra på att skratta',
  'Sidbena med lite väl långt hår',
  'Drog till Barselona, hyrde en limo',
  'Jag tror inte att det är så, men vore det inte intressant',
  'Jag hade en peng i fickan',
  'Han skulle gå och köpa Glocken Gold och kom aldrig tillbaka',
  'Alla drabbas och jag är en av dom',
  'Fan, den här kuken smakar snus',
  'Egentligen var det Google som sökte efter saker om dig',
  'Risk för köbildning', // 50
  'Bara för att de är kända behöver de inte vara fina människor',
  'Halal-öl och sånna grejer',
  'En blixt blandat med laser',
  'Har du lyssnat på Anneli',
  'Konflikt och oftast fint väder',
  'Pengarna används sedan för att bekämpa fattigdom genom trädplantering,',
  'Förlåt jag mena det inte, jag bara kände för det',
  'De hände asså',
  'Du blockar min periferi', // 60
  'Ingen kan klä sig så och komma undan med det',
  'Det är klart som gatan',
  'Livet är inte bara skit. Det är piss också',
  'Fy fan vad lätt det är att få känsla',
  'Spela Yatzy och Plocke-pinn är ju bara kul i 5 veckor',
  'Dansberget är ju här',
  'Men jag väljer fan att tro på det',
  'Jag skulle aldrig någonsin lämna någon',
  'Jag vet inte, lika mycket som en större båt',
  'Är det någon som har sin mobil med sig?', // 70
  'Advokaten har inen fru',
  'Om jag inte får den njutningen, då har jag ingenting kvar',
  'Allt måste göra skillnad',
  'Jag har alltid varit rädd för att börja hata',
  'Skön amerikansk sosialism',
  'Jag ser ut som en hel succé',
  'En stark kvinnlig karaktär som syns mycket i bakgrunden',
  'Jag förstår, du vill förklara för mig',
  'Hassla tills jag blir yr',
  'Drick utan sans', // 80
  'Du kan inte jämföra gud med ett får',
  'Hinna så lite som möjligt',
  'Bodegård är död',
  'Erfaren är man när det händer grejer',
  'Vi har i alla fall snus',
  'En whiskey, kanske ett plåster',
  'Tjejerna fick ta notan',
  'Han kommer tyvärr aldrig få huvudrollen',
  'Plugga som en jävla gangster',
  'Jag kommer inte känna något', // 90
  'Gå med ibland gratis',
  'Lite ägg och alkohol',
  'Jag har ingen bärs, jag har ingenting',
  'Vi vill gärna behålla dimman',
  'Börja med en Volvo, sluta i Rom'
]

export default quotes
